'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''show_app_settings class.
'''</summary>
'''<remarks>
'''Auto-generated class.
'''</remarks>
Partial Public Class show_app_settings

	'''<summary>
	'''divSettings control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents divSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''txtServerName control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents txtServerName As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''butShowConnectionString control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents butShowConnectionString As Global.System.Web.UI.WebControls.Button
End Class
